version: '3'
services:
  productsapi:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=$SERVER_PORT
    image: products-api
    ports:
      - 9000:9000
    volumes:
      - ./products-api:/code
  